#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin/debug
go build -tags "tcmu qcow debug" -ldflags "-X main.VERSION=$VERSION -linkmode external -extldflags -static" -o bin/debug/longhorn
