#!/bin/bash

anywait() {
  for pid in "$@"; do
    while kill -0 "$pid"; do
      sleep 0.5
    done
  done
}

if [ -z "$JIVA_CTL_IP" ]; then
  echo 'Please set $JIVA_CTL_IP'
  exit
fi

if [ -z "$JIVA_REP_NAME" ]; then
  echo 'Please set $JIVA_REP_NAME'
  exit
fi

if [ -z "$JIVA_REP_VERSION" ]; then
  echo 'Please set $JIVA_REP_VERSION'
  exit
fi

if [ -z "$JIVA_REP_VOLNAME" ]; then
  echo 'Please set $JIVA_REP_VOLNAME'
  exit
fi

if [ -z "$JIVA_REP_VOLSTORE" ]; then
  echo 'Please set $JIVA_REP_VOLSTORE'
  exit
fi

if [ -z "$JIVA_REP_VOLSIZE" ]; then
  echo 'Please set $JIVA_REP_VOLSIZE'
  exit
fi

if [ -z "$JIVA_REP_IFACE" ]; then
  echo 'Please set $JIVA_REP_IFACE'
  exit
fi

if [ -z "$JIVA_REP_IP" ]; then
  echo 'Please set $JIVA_REP_IP'
  exit
fi

if [ -z "$JIVA_REP_SUBNET" ]; then
  echo 'Please set $JIVA_REP_SUBNET'
  exit
fi

echo "Stopping container $JIVA_REP_NAME"
docker stop $JIVA_REP_NAME

echo "Removing container $JIVA_REP_NAME"
docker rm $JIVA_REP_NAME

if ! [ -z "$JIVA_REP_ENVSUBST" ]; then
  echo "Replacing environment variables in $JIVA_REP_COMMAND"
  JIVA_REP_COMMAND=$(echo $JIVA_REP_COMMAND | envsubst)
fi


echo "Configuring $JIVA_REP_IP/$JIVA_REP_SUBNET on $JIVA_REP_IFACE"
#TODO - Validate if the IP exists on the right interface
#TODO - Validate that interface exists
sudo ip addr add $JIVA_REP_IP/$JIVA_REP_SUBNET dev $JIVA_REP_IFACE
#TODO - Validate that IP is configured successfully

_stop() {
  echo "Stopping container $JIVA_REP_NAME"
  until docker stop $JIVA_REP_NAME
  do
    sleep 1
  done
}

echo "Trapping SIGINT, SIGTERM and SIGKILL"
trap _stop SIGINT
trap _stop SIGTERM

echo "Starting container $JIVA_REP_NAME"
CONTAINER_ID=$(docker run -d \
  --network="host" \
  -p $JIVA_REP_IP:9502:9502 \
  -p $JIVA_REP_IP:9503:9503 \
  -p $JIVA_REP_IP:9504:9504 \
  --name $JIVA_REP_NAME \
  -v $JIVA_REP_VOLSTORE:/$JIVA_REP_VOLNAME \
  $JIVA_REP_VERSION \
  launch replica \
  --frontendIP $JIVA_CTL_IP \
  --listen $JIVA_REP_IP:9502 \
  --size $JIVA_REP_VOLSIZE \
  /$JIVA_REP_VOLNAME)

if [ $? -ne 0 ]; then
  echo "Failed to start $JIVA_REP_NAME"
  exit
fi

echo "Waiting for container $JIVA_REP_NAME ($CONTAINER_ID) to finish"
PID=$(ps aux | grep "docker-containerd-shim $CONTAINER_ID" | grep -v "grep" | awk '{print $2}')
anywait $PID
