#!/bin/bash

anywait() {
  for pid in "$@"; do
    while kill -0 "$pid"; do
      sleep 0.5
    done
  done
}

cleanup() { 
  if [ ! -z "$CONTAINER_ID" ]; then
    while true; 
    do
      docker ps | grep $CONTAINER_ID
      if [ $? -ne 0 ]; then
        sudo ip addr del $JIVA_CTL_IP/$JIVA_CTL_SUBNET dev $JIVA_CTL_IFACE
        break;
      fi
      sleep 10
    done
  fi
}


if [ -z "$JIVA_CTL_NAME" ]; then
  echo 'Please set $JIVA_CTL_NAME'
  exit
fi

if [ -z "$JIVA_CTL_VERSION" ]; then
  echo 'Please set $JIVA_CTL_VERSION'
  exit
fi

if [ -z "$JIVA_CTL_VOLNAME" ]; then
  echo 'Please set $JIVA_CTL_VOLNAME'
  exit
fi

if [ -z "$JIVA_CTL_VOLSIZE" ]; then
  echo 'Please set $JIVA_CTL_VOLSIZE'
  exit
fi

if [ -z "$JIVA_CTL_IFACE" ]; then
  echo 'Please set $JIVA_CTL_IFACE'
  exit
fi

if [ -z "$JIVA_CTL_IP" ]; then
  echo 'Please set $JIVA_CTL_IP'
  exit
fi

if [ -z "$JIVA_CTL_SUBNET" ]; then
  echo 'Please set $JIVA_CTL_SUBNET'
  exit
fi

echo "Stopping container $JIVA_CTL_NAME"
docker stop $JIVA_CTL_NAME

echo "Removing container $JIVA_CTL_NAME"
docker rm $JIVA_CTL_NAME

if ! [ -z "$JIVA_CTL_ENVSUBST" ]; then
  echo "Replacing environment variables in $JIVA_CTL_COMMAND"
  JIVA_CTL_COMMAND=$(echo $JIVA_CTL_COMMAND | envsubst)
fi


echo "Configuring $JIVA_CTL_IP/$JIVA_CTL_SUBNET on $JIVA_CTL_IFACE"
#TODO - Validate if the IP exists on the right interface
#TODO - Validate that interface exists
sudo ip addr add $JIVA_CTL_IP/$JIVA_CTL_SUBNET dev $JIVA_CTL_IFACE
#TODO - Validate that IP is configured successfully

_stop() {
  echo "Stopping container $JIVA_CTL_NAME"
  until docker stop $JIVA_CTL_NAME
  do
    sleep 1
  done
}

echo "Trapping SIGINT, SIGTERM and SIGKILL"
#trap _stop SIGINT
#trap _stop SIGTERM

echo "Starting container $JIVA_CTL_NAME"
CONTAINER_ID=$(docker run -d \
  --network="host" \
  -p $JIVA_CTL_IP:3260:3260 \
  -p $JIVA_CTL_IP:9501:9501 \
  --name $JIVA_CTL_NAME \
  $JIVA_CTL_VERSION \
  launch controller \
  --frontend gotgt \
  --frontendIP $JIVA_CTL_IP \
  $JIVA_CTL_VOLNAME\
  $JIVA_CTL_VOLSIZE)

if [ $? -ne 0 ]; then
  echo "Failed to start $JIVA_CTL_NAME"
  exit
fi

echo "Waiting for container $JIVA_CTL_NAME ($CONTAINER_ID) to finish"
PID=$(ps aux | grep "docker-containerd-shim $CONTAINER_ID" | grep -v "grep" | awk '{print $2}')
anywait $PID
#cleanup
