#!/bin/bash

KEEP_ALIVE=false
anywait() {
  while ${KEEP_ALIVE}; 
  do
    sleep 10
  done
}



if [ -z "$JIVA_CTL_IP" ]; then
  echo 'Please set $JIVA_CTL_IP'
  exit
fi

if [ -z "$JIVA_REP_NAME" ]; then
  echo 'Please set $JIVA_REP_NAME'
  exit
fi

if [ -z "$JIVA_REP_VERSION" ]; then
  echo 'Please set $JIVA_REP_VERSION'
  exit
fi

if [ -z "$JIVA_REP_VOLNAME" ]; then
  echo 'Please set $JIVA_REP_VOLNAME'
  exit
fi

if [ -z "$JIVA_REP_VOLSTORE" ]; then
  echo 'Please set $JIVA_REP_VOLSTORE'
  exit
fi

if [ -z "$JIVA_REP_VOLSIZE" ]; then
  echo 'Please set $JIVA_REP_VOLSIZE'
  exit
fi

if [ -z "$JIVA_REP_IFACE" ]; then
  echo 'Please set $JIVA_REP_IFACE'
  exit
fi

# The rep ip variable name can be:
# JIVA_REP_IP or
# JIVA_REP_IP_0
# The suffix is equal to value of NOMAD_ALLOC_INDEX
#
# NOTE:
#   Below are valid invocations w.r.t replica ip
#
#   JIVA_REP_IP="1.2.1.2" ./launch-jiva-rep-with-ip2
#   JIVA_REP_IP_1="1.2.1.2" NOMAD_ALLOC_INDEX="1" ./launch-jiva-rep-with-ip2
#   JIVA_REP_IP_2="1.2.1.3" NOMAD_ALLOC_INDEX="2" ./launch-jiva-rep-with-ip2
if [ ! -z "$NOMAD_ALLOC_INDEX" ]; then
  JIVA_REP_IP_VAR="JIVA_REP_IP_$NOMAD_ALLOC_INDEX"
else
  JIVA_REP_IP_VAR="JIVA_REP_IP"
fi

# use of indirection ${!PARAMETER} to interpolate nested variable
if [ -z "${!JIVA_REP_IP_VAR}" ]; then
  echo 'Please set $JIVA_REP_IP'
  exit
else
  # Set the replica IP addr meant for this replica instance
  JIVA_REP_IP=${!JIVA_REP_IP_VAR}
fi

if [ -z "$JIVA_REP_SUBNET" ]; then
  echo 'Please set $JIVA_REP_SUBNET'
  exit
fi

echo "Stopping container $JIVA_REP_NAME"
docker stop $JIVA_REP_NAME

echo "Removing container $JIVA_REP_NAME"
docker rm $JIVA_REP_NAME

if ! [ -z "$JIVA_REP_ENVSUBST" ]; then
  echo "Replacing environment variables in $JIVA_REP_COMMAND"
  JIVA_REP_COMMAND=$(echo $JIVA_REP_COMMAND | envsubst)
fi


echo "Configuring $JIVA_REP_IP/$JIVA_REP_SUBNET on $JIVA_REP_IFACE"
#TODO - Validate if the IP exists on the right interface
#TODO - Validate that interface exists
sudo ip addr add $JIVA_REP_IP/$JIVA_REP_SUBNET dev $JIVA_REP_IFACE
mkdir -p $JIVA_REP_VOLSTORE
#TODO - Validate that IP is configured successfully

_stop() {
  echo "Stopping container $JIVA_REP_NAME"
  until docker stop $JIVA_REP_NAME
  do
    sleep 1
  done
  echo "Clear the $JIVA_REP_IP"
  sudo ip addr del $JIVA_REP_IP/$JIVA_REP_SUBNET dev $JIVA_REP_IFACE
  KEEP_ALIVE=false
}

echo "Trapping SIGINT, SIGTERM and SIGKILL"
trap _stop SIGINT
trap _stop SIGTERM

echo "Starting container $JIVA_REP_NAME"
CONTAINER_ID=$(docker run -d \
  --network="host" \
  -p $JIVA_REP_IP:9502:9502 \
  -p $JIVA_REP_IP:9503:9503 \
  -p $JIVA_REP_IP:9504:9504 \
  --expose 9700-9800 \
  --name $JIVA_REP_NAME \
  -v $JIVA_REP_VOLSTORE:/$JIVA_REP_VOLNAME \
  $JIVA_REP_VERSION \
  launch replica \
  --frontendIP $JIVA_CTL_IP \
  --listen $JIVA_REP_IP:9502 \
  --size $JIVA_REP_VOLSIZE \
  /$JIVA_REP_VOLNAME)

if [ $? -ne 0 ]; then
  echo "Failed to start $JIVA_REP_NAME"
  exit 1
fi

echo "Launched container $JIVA_REP_NAME ($CONTAINER_ID)"
KEEP_ALIVE=true
anywait

