#!/bin/bash

KEEP_ALIVE=false
anywait() {
  while ${KEEP_ALIVE}; 
  do
    sleep 10
  done
}

if [ -z "$JIVA_CTL_NAME" ]; then
  echo 'Please set $JIVA_CTL_NAME'
  exit
fi

if [ -z "$JIVA_CTL_VERSION" ]; then
  echo 'Please set $JIVA_CTL_VERSION'
  exit
fi

if [ -z "$JIVA_CTL_VOLNAME" ]; then
  echo 'Please set $JIVA_CTL_VOLNAME'
  exit
fi

if [ -z "$JIVA_CTL_VOLSIZE" ]; then
  echo 'Please set $JIVA_CTL_VOLSIZE'
  exit
fi

if [ -z "$JIVA_CTL_IFACE" ]; then
  echo 'Please set $JIVA_CTL_IFACE'
  exit
fi

if [ -z "$JIVA_CTL_IP" ]; then
  echo 'Please set $JIVA_CTL_IP'
  exit
fi

if ping -c1 -W2 $JIVA_CTL_IP
then
	exit
fi

if [ -z "$JIVA_CTL_SUBNET" ]; then
  echo 'Please set $JIVA_CTL_SUBNET'
  exit
fi

echo "Stopping container $JIVA_CTL_NAME"
docker stop $JIVA_CTL_NAME

echo "Removing container $JIVA_CTL_NAME"
docker rm $JIVA_CTL_NAME

if ! [ -z "$JIVA_CTL_ENVSUBST" ]; then
  echo "Replacing environment variables in $JIVA_CTL_COMMAND"
  JIVA_CTL_COMMAND=$(echo $JIVA_CTL_COMMAND | envsubst)
fi


echo "Configuring $JIVA_CTL_IP/$JIVA_CTL_SUBNET on $JIVA_CTL_IFACE"
#TODO - Validate if the IP exists on the right interface
#TODO - Validate that interface exists
sudo ip addr add $JIVA_CTL_IP/$JIVA_CTL_SUBNET dev $JIVA_CTL_IFACE
#TODO - Validate that IP is configured successfully

_stop() {
  echo "Stopping container $JIVA_CTL_NAME"
  until docker stop $JIVA_CTL_NAME
  do
    sleep 1
  done
  echo "Clearing the IP $JIVA_CTL_IP"
  sudo ip addr del $JIVA_CTL_IP/$JIVA_CTL_SUBNET dev $JIVA_CTL_IFACE
  KEEP_ALIVE=false
}

echo "Trapping SIGINT, SIGTERM and SIGKILL"
trap _stop SIGINT
trap _stop SIGTERM

#Dont set the name to avoid deleting failed containers

echo "Starting container $JIVA_CTL_NAME"
CONTAINER_ID=$(docker run -d \
  --network="host" \
  --name $JIVA_CTL_NAME \
  -p $JIVA_CTL_IP:3260:3260 \
  -p $JIVA_CTL_IP:9501:9501 \
  $JIVA_CTL_VERSION \
  launch controller \
  --frontend gotgt \
  --frontendIP $JIVA_CTL_IP \
  $JIVA_CTL_VOLNAME\
  $JIVA_CTL_VOLSIZE)

if [ $? -ne 0 ]; then
  echo "Failed to start $JIVA_CTL_NAME"
  exit
fi

echo "Launched container $JIVA_CTL_NAME ($CONTAINER_ID)"
KEEP_ALIVE=true
anywait
