#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}-DEBUG}
# IMAGE_ORG can be used to customize the organization 
# under which images should be pushed. 
# By default the organization name is `openebs`. 
IMAGE_ORG=${IMAGE_ORG:-openebs}

BASE_DOCKER_IMAGEARM64=${BASE_DOCKER_IMAGEARM64:-arm64v8/ubuntu:18.04}
BASE_DOCKER_IMAGEPPC64LE=${BASE_DOCKER_IMAGEPPC64LE:-ubuntu:18.04}

if [ ! -x ../bin/debug/longhorn ]; then
    ../scripts/build_debug_binaries
fi

cp ../bin/debug/longhorn* .
#cp /usr/src/tgt/pkg/tgt_*.deb .
if [ ${ARCH} == "linux_arm64" ]
then
  DOCKERFILE=Dockerfile_build_arm64
  docker build -f ${DOCKERFILE} -t ${IMAGE_ORG}/jiva-${XC_ARCH}:${TAG} --build-arg BASE_IMAGE=${BASE_DOCKER_IMAGEARM64} .
elif [ ${ARCH} == "linux_ppc64le" ]
then
  DOCKERFILE=Dockerfile_build_ppc64le
  docker build -f ${DOCKERFILE} -t ${IMAGE_ORG}/jiva-${XC_ARCH}:${TAG} --build-arg BASE_IMAGE=${BASE_DOCKER_IMAGEPPC64LE} .
else
  DOCKERFILE=Dockerfile_build_amd64
  docker build -f ${DOCKERFILE} -t ${IMAGE_ORG}/jiva:${TAG} .
fi
echo Built ${IMAGE_ORG}/jiva-${XC_ARCH}:${TAG}
