#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}}
REPO=${REPO:-openebs}

if [ ! -x ../bin/longhorn ]; then
    ../scripts/build_binaries
fi

cp ../bin/longhorn* .
cp ../bin/longhorn jivactl
#cp /usr/src/tgt/pkg/tgt_*.deb .
if [ ${ARCH} == "linux_arm64" ]
then
  DOCKERFILE=Dockerfile_build_arm64
  docker build -f ${DOCKERFILE} -t ${REPO}/jiva-${XC_ARCH}:${TAG} .
else
  DOCKERFILE=Dockerfile_build_amd64
  docker build -f ${DOCKERFILE} -t ${REPO}/jiva:${TAG} .
fi
echo Built ${REPO}/jiva-${XC_ARCH}:${TAG}
