#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}-DEBUG}
REPO=${REPO:-openebs}
BASE_DOCKER_IMAGEARM64=${BASE_DOCKER_IMAGEARM64:-arm64v8/ubuntu:18.04}

if [ ! -x ../bin/debug/longhorn ]; then
    ../scripts/build_debug_binaries
fi

cp ../bin/debug/longhorn* .
#cp /usr/src/tgt/pkg/tgt_*.deb .
if [ ${ARCH} == "linux_arm64" ]
then
  DOCKERFILE=Dockerfile_build_arm64
  docker build -f ${DOCKERFILE} -t ${REPO}/jiva-${XC_ARCH}:${TAG} --build-arg BASE_IMAGE=${BASE_DOCKER_IMAGEARM64} .
else
  DOCKERFILE=Dockerfile_build_amd64
  docker build -f ${DOCKERFILE} -t ${REPO}/jiva:${TAG} .
fi
echo Built ${REPO}/jiva-${XC_ARCH}:${TAG}
