#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}}

# IMAGE_ORG can be used to customize the organization 
# under which images should be pushed. 
# By default the organization name is `openebs`. 
IMAGE_ORG=${IMAGE_ORG:-openebs}

BASE_DOCKER_IMAGEARM64=${BASE_DOCKER_IMAGEARM64:-arm64v8/ubuntu:18.04}
BASE_DOCKER_IMAGEPPC64LE=${BASE_DOCKER_IMAGEPPC64LE:-ubuntu:18.04}

# Specify the date of build
DBUILD_DATE=$(date +'%Y-%m-%dT%H:%M:%SZ')

# Specify the docker arg for repository url
if [ -z "${DBUILD_REPO_URL}" ]; then
  DBUILD_REPO_URL="https://github.com/openebs/jiva"
fi

# Specify the docker arg for website url
if [ -z "${DBUILD_SITE_URL}" ]; then
  DBUILD_SITE_URL="https://openebs.io"
fi

DBUILD_ARGS="--build-arg DBUILD_DATE=${DBUILD_DATE} --build-arg DBUILD_REPO_URL=${DBUILD_REPO_URL} --build-arg DBUILD_SITE_URL=${DBUILD_SITE_URL} --build-arg ARCH=${ARCH}"

if [ ! -x ../bin/longhorn ]; then
    ../scripts/build_binaries
fi

cp ../bin/longhorn* .
cp ../bin/longhorn jivactl
#cp /usr/src/tgt/pkg/tgt_*.deb .
if [ ${ARCH} == "linux_arm64" ]
then
  DOCKERFILE=Dockerfile_build_arm64
  docker build -f ${DOCKERFILE} -t ${IMAGE_ORG}/jiva-${XC_ARCH}:${TAG} ${DBUILD_ARGS} --build-arg BASE_IMAGE=${BASE_DOCKER_IMAGEARM64} .
elif [ ${ARCH} == "linux_ppc64le" ]
then
  DOCKERFILE=Dockerfile_build_ppc64le
  docker build -f ${DOCKERFILE} -t ${IMAGE_ORG}/jiva-${XC_ARCH}:${TAG} ${DBUILD_ARGS} --build-arg BASE_IMAGE=${BASE_DOCKER_IMAGEPPC64LE} .
else
  DOCKERFILE=Dockerfile_build_amd64
  docker build -f ${DOCKERFILE} -t ${IMAGE_ORG}/jiva:${TAG} ${DBUILD_ARGS} .
fi
echo Built ${IMAGE_ORG}/jiva-${XC_ARCH}:${TAG}
