#!/bin/bash
set -e

source "$(dirname $0)/version"
IMAGEID=$( docker images -q openebs/jiva:${VERSION} )

if [ ! -z "${DNAME}" ] && [ ! -z "${DPASS}" ]; 
then 
  docker login -u "${DNAME}" -p "${DPASS}"; 
  #Push the development build images to jiva-ci docker hub repository
  docker tag ${IMAGEID} openebs/jiva-ci:${VERSION}
  docker push openebs/jiva-ci:${VERSION};
  docker tag ${IMAGEID} openebs/jiva:ci
  docker push openebs/jiva:ci;
  if [ ! -z "${TRAVIS_TAG}" ] && [ "${TRAVIS_BRANCH}" == "master" ];
  then
    docker tag ${IMAGEID} openebs/jiva:${TRAVIS_TAG}
    docker push openebs/jiva:${TRAVIS_TAG};
    docker tag ${IMAGEID} openebs/jiva:latest
    docker push openebs/jiva:latest;
  fi;
else
  echo "No docker credentials provided. Skip uploading openebs/jiva:${VERSION} to docker hub"; 
fi;
