#!/bin/bash
set -e

cd $(dirname $0)/..

echo Running tests

PACKAGES="$(find . -name '*.go' | xargs -I{} dirname {} | sort -u | grep -Ev '(.git|.trash-cache|vendor|bin)')"

echo Packages: ${PACKAGES}

HOST_ARCH="$(go env GOHOSTARCH)"

[ "${HOST_ARCH}" == "amd64" ] && RACE=-race
[ "${HOST_ARCH}" == "${XC_ARCH}" ] && go test ${RACE} -cover -tags="test qcow" ${PACKAGES}
echo "Finish test ..."
