#!/bin/bash

set -x
# Generate a uniqe tag based on the commit and tag
BUILD_ID=$(git describe --tags --always)

# Determine the current branch
CURRENT_BRANCH=""
if [ -z ${TRAVIS_BRANCH} ];
then
  CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
else
  CURRENT_BRANCH=${TRAVIS_BRANCH}
fi

#Depending on the branch where builds are generated, 
# set the tag CI (fixed) and build tags.
BUILD_TAG="${CURRENT_BRANCH}-${BUILD_ID}"
CI_TAG="${CURRENT_BRANCH}-ci"
if [ ${CURRENT_BRANCH} = "master" ]; then
  CI_TAG="ci"
fi

echo "Set the fixed ci image tag as: ${CI_TAG}"
echo "Set the build/unique image tag as: ${BUILD_TAG}"

COMMIT=$(git rev-parse --short HEAD)
BUILDDATE=$(date --rfc-3339=seconds)
BUILDDATE=${BUILDDATE// /,} # skip spaces from above and add comma

if [ ! -z "${TRAVIS_TAG}" ] ;
  then
    GITCOMMIT=${COMMIT}
    VERSION=${TRAVIS_TAG}
else
  RELEASE_TAG=${CI_TAG}
  GITCOMMIT=${COMMIT}
  VERSION=${RELEASE_TAG}-${COMMIT}
fi;

echo "Git commit id: $GITCOMMIT"
echo "Jiva version: $VERSION"
echo "Build date: $BUILDDATE"
