#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}}
REPO=${REPO:-openebs}

if [ ! -x ../bin/longhorn ]; then
    ../scripts/build
fi

cp ../bin/longhorn* .
cp /usr/src/tgt/pkg/tgt_*.deb .
docker build -t ${REPO}/jiva:${TAG} .

echo Built ${REPO}/jiva:${TAG}
