#!/bin/bash
set -e

source "$(dirname $0)/version"
IMAGEID=$( docker images -q openebs/jiva:${VERSION} )

if [ ! -z "${DNAME}" ] && [ ! -z "${DPASS}" ]; 
then 
  docker login -u "${DNAME}" -p "${DPASS}"; 
  #Push the development build images to jiva-ci docker hub repository
  docker tag ${IMAGEID} openebs/jiva-ci:${VERSION}
  docker push openebs/jiva-ci:${VERSION} ; 
  if [ ! -z "${TRAVIS_TAG}" ] ; 
  then
    #Push the release tag image to jiva docker hub repository
    #When a git hub is tagged with a release, the travis will 
    #hold the release tag in env TRAVIS_TAG
    docker tag ${IMAGEID} openebs/jiva:${TRAVIS_TAG}
    docker push openebs/jiva:${TRAVIS_TAG}; 
    docker tag ${IMAGEID} openebs/jiva:latest
    docker push openebs/jiva:latest; 
  fi;
else
  echo "No docker credentials provided. Skip uploading openebs/jiva:${VERSION} to docker hub"; 
fi;
