From arm64v8/ubuntu:18.04
RUN apt-get update && apt-get install -y curl \
    && rm -rf /var/lib/apt/lists/*

COPY longhorn jivactl launch copy-binary launch-with-vm-backing-file launch-simple-jiva /usr/local/bin/

VOLUME /usr/local/bin
CMD ["longhorn"]
