#!/bin/bash

# Copyright © 2020 The OpenEBS Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -x
set -e
#mount --rbind /host/dev /dev

volume=$1
size=$2
frontend=$3

if [ -z $volume ]
then
        echo "Usage: launch-simple-longhorn <volume_name> <frontend> "
        echo "<volume_name>: Required. User defined volume name"
        echo "<frontend>: Optional. By default 'tcmu'. "
	exit -1
fi

if [ -z $size ]
then
        echo Use default size 1g
        size="1g"
fi

if [ -z $frontend ]
then
        echo Use default frontend TCMU
        frontend="tcmu"
fi

longhorn replica --size $size --listen localhost:9502 /volume/ &
sleep 1
exec longhorn controller --frontend $frontend --replica tcp://localhost:9502 $volume
