#!/usr/bin/env bash

# This file was originally authored by Rancher Labs
# under Apache License 2018.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

BASE_IMAGE_DIR_LIST=( `ls /base_image` )
if [ ${#BASE_IMAGE_DIR_LIST[@]} -ne 1 ]; then
  echo "/base_image directory must contain exactly one base image file"
  exit 1
fi
IMAGE_FILE="/base_image/${BASE_IMAGE_DIR_LIST[0]}"

COMMAND=$1
shift
if [ "${COMMAND}" == "replica" ]; then
    /cmd/longhorn ${COMMAND} --backing-file ${IMAGE_FILE}  "$@"
elif [ "${COMMAND}" == "sync-agent" ]; then
    /cmd/longhorn ${COMMAND} "$@"
else
    echo "Bad command: ${COMMAND}"
    exit 1
fi
